# Generated by Selenium IDE
import pytest
import time
import json
from datetime import datetime
import glob
import os
import shutil
import sqlAPI_tillamook
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

DOWNLOAD_DIR = os.path.join(os.getcwd(), "tillamook_downloads")
STAGING_DIR = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "files_to_data_bricks", "Tillamook")
)


class tillamook_export():

    def setup_method(self, method):
        os.makedirs(DOWNLOAD_DIR, exist_ok=True)
        options = webdriver.ChromeOptions()
        prefs = {
            "download.default_directory": DOWNLOAD_DIR,
            "download.prompt_for_download": False,
        }
        options.add_experimental_option("prefs", prefs)
        self.driver = webdriver.Chrome(options=options)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def export_tillamook(self):
        farms = sqlAPI_tillamook.list_of_farms()
        for farm in farms:
            self.driver.get("https://tillamookproducers.com/Home/Login")
            self.driver.find_element(By.ID, "Username").click()
            self.driver.find_element(By.ID, "Username").send_keys(farm[1])
            self.driver.find_element(By.ID, "passwordInput").click()
            self.driver.find_element(By.ID, "passwordInput").send_keys(farm[2])
            self.driver.find_element(By.ID, "loginBtn").click()
            time.sleep(4)
            files_before = set(glob.glob(os.path.join(DOWNLOAD_DIR, "*.csv")))
            self.driver.find_element(By.CSS_SELECTOR, "#rbdComponentresults_wrapper .buttons-csv > span").click()
            downloaded_file = self.wait_for_download(files_before)
            date_str = datetime.now().strftime("%Y%m%d")
            farm_slug = farm[0].replace(" ", "_")
            farm_dir = os.path.join(DOWNLOAD_DIR, farm_slug)
            os.makedirs(farm_dir, exist_ok=True)
            new_name = f"{date_str}_{farm_slug}_productiondata.csv"
            new_path = os.path.join(farm_dir, new_name)
            os.rename(downloaded_file, new_path)
            print(f"Renamed to: {new_path}")
        self._move_tillamook_downloads_to_staging()

    def _move_tillamook_downloads_to_staging(self):
        """Move per-farm subfolders from tillamook_downloads/ to files_to_data_bricks/Tillamook/."""
        os.makedirs(STAGING_DIR, exist_ok=True)
        for item in os.listdir(DOWNLOAD_DIR):
            src = os.path.join(DOWNLOAD_DIR, item)
            if not os.path.isdir(src):
                continue
            dest = os.path.join(STAGING_DIR, item)
            if not os.path.exists(dest):
                shutil.move(src, dest)
                print(f"Moved: {src} -> {dest}")
                continue
            for fname in os.listdir(src):
                fsrc = os.path.join(src, fname)
                if not os.path.isfile(fsrc):
                    continue
                fdest = os.path.join(dest, fname)
                if os.path.exists(fdest):
                    print(f"Skip (exists in staging): {fdest}")
                    continue
                shutil.move(fsrc, fdest)
                print(f"Moved: {fsrc} -> {fdest}")
            try:
                if not os.listdir(src):
                    os.rmdir(src)
            except OSError:
                pass

    def wait_for_download(self, files_before, timeout=60):
        end_time = time.time() + timeout
        while time.time() < end_time:
            files_now = set(glob.glob(os.path.join(DOWNLOAD_DIR, "*.csv")))
            new_files = files_now - files_before
            if new_files:
                new_file = new_files.pop()
                if not new_file.endswith(".crdownload"):
                    print(f"Download complete: {new_file}")
                    return new_file
            time.sleep(1)
        raise TimeoutError("Download did not complete within the timeout period.")


if __name__ == "__main__":
    exporter = tillamook_export()
    exporter.setup_method(None)
    try:
        exporter.export_tillamook()
    finally:
        exporter.teardown_method(None)
