# Generated by Selenium IDE
import pytest
import time
import json
import glob
import os
import sqlAPI_tillamook
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

DOWNLOAD_DIR = os.path.join(os.getcwd(), "tillamook_downloads")


class tillamook_export():

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def export_tillamook(self):
        farms = sqlAPI_tillamook.list_of_farms()
        for farm in farms:
            self.driver.get("https://tillamookproducers.com/Home/Login")
            self.driver.find_element(By.ID, "Username").click()
            self.driver.find_element(By.ID, "Username").send_keys(farm[1])
            self.driver.find_element(By.ID, "passwordInput").click()
            self.driver.find_element(By.ID, "passwordInput").send_keys(farm[2])
            self.driver.find_element(By.ID, "loginBtn").click()
            time.sleep(4)
            files_before = set(glob.glob(os.path.join(DOWNLOAD_DIR, "*.csv")))
            self.driver.find_element(By.CSS_SELECTOR, "#rbdComponentresults_wrapper .buttons-csv > span").click()
            self.wait_for_download(files_before)

    def wait_for_download(self, files_before, timeout=60):
        end_time = time.time() + timeout
        while time.time() < end_time:
            files_now = set(glob.glob(os.path.join(DOWNLOAD_DIR, "*.csv")))
            new_files = files_now - files_before
            if new_files:
                new_file = new_files.pop()
                if not new_file.endswith(".crdownload"):
                    print(f"Download complete: {new_file}")
                    return new_file
            time.sleep(1)
        raise TimeoutError("Download did not complete within the timeout period.")


if __name__ == "__main__":
    exporter = tillamook_export()
    exporter.setup_method(None)
    try:
        exporter.export_tillamook()
    finally:
        exporter.teardown_method(None)
